# Generated by Django 3.0.5 on 2020-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatistics',
            name='batting_over',
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstatistics',
            name='balls_played',
            field=models.FloatField(default=0.0, verbose_name='Balls'),
        ),
    ]
