# Generated by Django 3.0.5 on 2020-05-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_auto_20200503_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.ProtectedError, related_name='Winner', to='cricket.Team', verbose_name='Winner'),
        ),
    ]
