# Generated by Django 3.0.5 on 2020-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_match_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_overs',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Overs Played by Team1'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_overs',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Overs Played by Team1'),
        ),
    ]
